server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodshop
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: api/v1
jwt:
  expiration: 2592000 # 30day
  secretKey: 1j6z8Suwn+Aa5JDZTP3bCLEjQp+rzhUNinCndYzkAm0=